kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: caravana
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 3000
      - containerPort: 30001
        hostPort: 5173
      - containerPort: 30002
        hostPort: 27018